name: stock_flutter_app
description: "A Flutter stock application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  sqflite: ^2.4.2
  path: ^1.9.1
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
