name: stock_flutter_app
description: "A Flutter stock application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
